### PR TITLE
V1.27 patches

### PR DESCRIPTION
**Pull request by tali713**
Here we go, a few minor changes.

### CODE REVIEW

**Comment by Amostubal** [comment]
Okay so I guess you have some experience trading graphics in and out? because I'm dead in the water on that... It always confuses me. 
Where did you get the meph 16x16 I didn't even know that one existed.

**Comment by Amostubal** [comment]
I'm going to pull this into 1.27 planned... merge what I have on my system as an update into 1.27 planned... so I can sync my own to this and the other.  I'll test it a bit here. 
Test it out however you can on your end and let me know if you find any errors.  I've got to complete the modest mill update.. which is going to require a bunch of small files in the graphic folders to be updated.

**Comment by Amostubal** [comment]
Hey tali! before you do anymore updates to graphics you will want to update to the current commit of 1.27-planned, and check the differences in plant_crop and plant_standard now...  I made the changes in the one you submitted.  Its necessary fixes to keep from breaking modest milling.

**Comment by Amostubal** [comment]
to be exact the changes in the graphics folders, since that is the version that will propagate over to the default raws on their own.

**Comment by tali713** [comment]
Thank you for the heads up.  I'll just reset my patch branch to v1.27-planned before I cherry pick any other changes, would you like me to propagate the default/meph succubi tiles to the rest of the graphics packs?

**Comment by Amostubal** [comment]
the question is should they be?

**Comment by tali713** [comment]
Well if the default isn't set in the others then the tiles won't reset if a different graphics pack is selected.  So one or the other should be in all the graphics packs.

**Comment by Amostubal** [comment]
then the answer is yes lol  I'll take all the help I can get!

**Comment by Amostubal** [comment]
ARe you really working on a mac set up of masterwork?  Really i need to get you into discord so I can chat direct with you... or am I already, lol.... so many on there aren't using the same names across domains.

**Pull request merged**
