### PR TITLE
V1.27 planned

### PR DESCRIPTION
**Pull request by tali713**
Just a typo, and some git ignorables.

### CODE REVIEW

**Comment by Amostubal** [comment]
So what's going on I just got the email on this.

**Comment by Amostubal** [comment]
It looked like good work...

**Comment by tali713** [comment]
I left the branch open, without realizing that github would keep adding it to the pull request.  Oops, will reopen in a new pull request in a few seconds.

**Comment by Amostubal** [comment]
Ok.  I'll look at it tomorrow.

**Comment by tali713** [comment]
See #28

**Pull request closed without merging**
