### PR TITLE
Comment out stale decoration overides, see: reaction_decoration.txt

### PR DESCRIPTION
**Pull request by tali713**
A barbaric, but probably necessary fix.  It appears that the TWBT spam is from these stale overrides.  I assume that the custom decoration workshops used to rely on these, but that has now changed.  Or I just broke the decorations, but I doubt it.  Regardless if they need to be restored they can be uncommented, if they are truly unnecessary, deleted.

### CODE REVIEW

**Comment by Amostubal** [comment]
one issue... there are 45 override files.  1 in each graphic pack.

**Comment by tali713** [comment]
Oh yes, I see, I'll take a look at that tonight.

**Comment by Amostubal** [comment]
yeah thats why I had to update and told you to update I just propagated a fix across 45 graphic packs this morning... It is a pain to make any changes to the files that get transferred with the graphics...  wish I could change the methods of the gui/launcher in doing this one thing.

**Comment by Amostubal** [comment]
I'll wait for the other fixes before I move this pull request.

**Comment by tali713** [comment]
Well, after some small investigation, trivial it is not.  Merely easy.  I'll sed it and update this pull request.

**Comment by tali713** [comment]
Closing this, will reopen in a clean pull request.

**Comment by tali713** [comment]
Reopened in #36

**Pull request closed without merging**
