### PR TITLE
Renamed SOUL_GEM to avoid duplicate material

### PR DESCRIPTION
**Pull request by ML-SolInvictus**
I'm still trying to figure how to work on GitHub

### CODE REVIEW

**Comment by Amostubal** [comment]
looks like you figured it out... yeah I was still learning how the gui worked when I made those changes.. and didn't realize they will dump a bunch of errors.  The issue is why we have the end of the file to avoid \"tag corruptions\"  the gui isn't using the same length for on and off of those tags... so if you turn on and off 80 tags you loose a line of \"\#\" I added at the end.

**Comment by Amostubal** [comment]
Some nice looking fixes, and renaming the soul gem is a good idea, but is it really that different from the other soul gem?  what I'm asking is there possibly a way to say toss 1 and keep the other, in preference the succubus one... or if we are going to rename them... if the other is ZM5s we could edit that version.  and not directly affecting the "primary" races.  Boltgun produces his own work, and I'd rather not edit the name every time he reloads them....  Then again.. I'm not even sure if Boltgun is using the soulgems in his work anymore.  I need to get a confirmation on that one.

**Comment by ML-SolInvictus** [comment]
I did choose to rename the soul gem from Succubus because, at the moment, it is not used.
Maybe we can ask Boltgun to rename the soul gem in is own mod.

**Comment by ML-SolInvictus** [comment]
I have other corrections to make but I do not have much time to dedicate and i still have to figure out how to submit separated commits

**Comment by Amostubal** [comment]
those creature issues are related to the fact that the skin/leather/parchment/etc wasn't removed from scale bearing beasts... they shouldn't be switched to skin... and I've never edited these creatures so that had to come from 1.23 as far as I remember.  the other guy I switched it to fat as temp, because meph had coded his skin material removed... not sure what was planned.

**Comment by Amostubal** [comment]
additionally if you use skin in one place or another it requires you to make a reference to leather too.  which makes these units produce scale and leather... I don't think that was the intention.

**Comment by Amostubal** [comment]
when you make a pull request it keeps adding all commits to that branch to the same pull request.  You can only make individual commits to your own branch.

I'm not going to argue it... I'm going to push it and reload it on my side and see what it looks like here.

**Comment by Amostubal** [comment]
i can always revert it later.

**Comment by Amostubal** [comment]
well we still have errors in those creatures... and I remember there is another with errors that i commented out at https://github.com/Amostubal/modified-MWDF/pull/18/commits/019d48d72cfb176235071cd68e60f4d6d3831cc8#diff-ff022e61173440f76bb6c54eb13636be

file name 
modified-MWDF/MWDF Project/Dwarf Fortress/raw/objects/creature_masterwork_fliers.txt

thats when I started trying to figure these guys out I now remember... I made the changes you reverted because they were in the errorlogs...

I hate creatures...

and I know your interested in ending the raw errors, but the other repeated issue is due to a quick fix for modest mill mods.  to revert to the original is to pull 3 lines out plant material templates that rebreaks the modest mills.... I plan to update modest mods in the pack "eventually" which would include the proper fixes that will allow those 3 lines to be removed and end those errors.

**Comment by ML-SolInvictus** [comment]
You are correct, the error is still there. When I checked the "standard leather" was switched on in the GUI. I forget to revert the switch and re-check.

My knowledge of the RAW is not good enough to properly fix those creatures.
On a side note, I read you were looking for the MW gui source. Did you check http://dffd.bay12games.com/file.php?id=12466?

**Comment by Amostubal** [comment]
Yes I have it... it scares me... and I'm not sure how much changed between 1.17 and 1.23.  After digging in it I did find the "tag/button" system.... which is what is broken in masterwork... But I'm not totally sure how the whole thing works, enough to make additions... It's in VB... I'm more python and Lua.   I've not touched VB in 13 years.

**Comment by Amostubal** [comment]
okay I think the skin issue in most of those is that we need to remove all the skin calls, make them scale, then remove skin/leather/parchment from the materials and the tissues and that should do it If you want to try that go ahead... I'm heading on to the next mod update.  think I'm going to "verify" the modest mod is up to date and then follow it with stahls armoury and grims historical arms....   the first, because It will fix a list of errorlog errors and the others because I promised them last update.

**Comment by Amostubal** [comment]
oh I think you will need to start a new pull request since I added this one in already... I'll be waiting on whatever you come up with.  Thanks for your help so far!

**Pull request merged**
