### PR TITLE
Updated succubus graphics for all packs

### PR DESCRIPTION
**Pull request by tali713**
* Meph will retain the meph tiles, all others will use the default
  boltgun tiles, following the principle of least surprise

### CODE REVIEW

**Comment by Amostubal** [comment]
good work... I'm glad to have your help on this.. the graphics are still a mystery to me... you don't happen to be a 3d model maker too?

**Comment by tali713** [comment]
Nope, just your average programmer.  Batch manipulating files, and spotting errors in data definitions I can do easily.  I'm pondering a cross platform rewrite of the launcher, but actually drawing pictures? Nope.

To make matters worse I'm a total DF newb.  I originally only cloned your repo so I could play masterwork on my mac.

**Comment by Amostubal** [comment]
have you seen the launcher? 
its in VB... It makes me want to puke.  but I'm not a programmer,  I do this for a hobby.  I have experience in c & c++, but its been years.  most recent experience has been python 2.7 and python 3.0 and lua all in data manipulation, not graphics, guis, etc.  I was considering learning pyQT and making a cross platform launcher for masterwork. it would be an undertaking.  I'm not sure what the linux and mac pack designers are using for a launcher. 
  If you want to get on something to chat about your ideas, maybe they mesh with my own.

**Comment by tali713** [comment]
I have looked at the launcher, it's a bit mad, I am honestly surprised it still functions.  Not to knock whoever built it, it works surprisingly well in wine for what its worth.  But it is maddening to even figure out which part does what.

Do you have a preferred IRC network?  I'm usually on freenode.

**Comment by Amostubal** [comment]
It's a madhouse built by madmen, like all of MDF.   The thing is actually a port/mod of the original LNP from 7 years ago...  I know where the tag switches/selectors are..  it took 3 days of reading to find them...  I can edit them.  I'm just not totally sure how much changed between 1.17 and 1.23... 1.27 really isn't a change just a bunch of bug fixes of the original files.

I use a lot of different services, discord is a primary for the mod community, just about every mod writer and dfhack scripted I logged into one of the 2 big communities, and certain mods have their own chat discord servers.  But I can use what ever is comfortable for you.  I know freenode.

**Pull request merged**
